### ISSUE TITLE
Unable to import project. Error EOF

### ISSUE THREAD

**Issue by Zumkato** [lair-framework/api-server#2]
MacBook-Pro:drones Zumkato$ ./drone-nmap_darwin_amd64 -k vjiAJxfAgPy35Gh9q kevgirxmlnmap.xml
2016/03/20 20:44:07 Fatal: Unable to import project. Error EOF

Getting this on all import.

Please let me know if you need an other information

**Comment by tomsteele** [comment]
There is probably something wrong with your LAIR_API_SERVER variable. I'd need to see an output of your listening services, including what IP and port they are listening on, as well as what you have LAIR_API_SERVER set to

**Comment by tomsteele** [comment]
@Zumkato if you need more help, feel free to ping me on here. Closing for now.
